spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&characterEncoding=UTF-8
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 10
      max-active: 15
      min-idle: 8
      max-wait: 10
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
mybatis:
#  config-location: classpath:mybatis/mybatisconfig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: info
  file:
    name: blog.log
    path: log